const keys = ['current','step','start','resume','done','waiting','progress','progressHint','history','sessions','view','next','ready','finished','saved','back','program','week','partial','error','retry','empty','details','coach','nutrition','all','nextSession'];
const values = {
  fr: ['Mon programme actuel','Une séance à la fois, vous avancez.','Commencer ma séance','Reprendre ma séance','Séances terminées','Votre coach prépare la suite. Vos résultats restent disponibles.','Mes progrès','Chaque séance compte. Retrouvez votre parcours et vos résultats.','Programmes terminés','Séances et résultats','Voir','Votre prochaine étape','Prêt','Programme terminé !','Séance enregistrée !','Retour à mon accueil','Mon programme','Semaine','En cours','Impossible de charger ce suivi.','Réessayer','Aucune séance enregistrée pour le moment.','Statistiques détaillées','Mon coach','Nutrition','Autres programmes','Prochaine séance'],
  en: ['My current programme','One session at a time, you move forward.','Start my session','Resume my session','Completed sessions','Your coach is preparing what comes next. Your results remain available.','My progress','Every session counts. Find your journey and results.','Completed programmes','Sessions and results','View','Your next step','Ready','Programme completed!','Session saved!','Back to my home','My programme','Week','In progress','Unable to load this progress.','Retry','No sessions recorded yet.','Detailed statistics','My coach','Nutrition','Other programmes','Next session'],
  es: ['Mi programa actual','Avanzas, una sesión a la vez.','Comenzar mi sesión','Reanudar mi sesión','Sesiones completadas','Tu entrenador está preparando la siguiente etapa. Tus resultados siguen disponibles.','Mi progreso','Cada sesión cuenta. Consulta tu recorrido y resultados.','Programas completados','Sesiones y resultados','Ver','Tu siguiente etapa','Listo','¡Programa completado!','¡Sesión guardada!','Volver al inicio','Mi programa','Semana','En curso','No se puede cargar este seguimiento.','Reintentar','Todavía no hay sesiones registradas.','Estadísticas detalladas','Mi entrenador','Nutrición','Otros programas','Próxima sesión'],
  it: ['Il mio programma attuale','Un allenamento alla volta, fai progressi.','Inizia la sessione','Riprendi la sessione','Sessioni completate','Il coach sta preparando la prossima fase. I risultati restano disponibili.','I miei progressi','Ogni sessione conta. Consulta il percorso e i risultati.','Programmi completati','Sessioni e risultati','Vedi','La prossima tappa','Pronto','Programma completato!','Sessione salvata!','Torna alla home','Il mio programma','Settimana','In corso','Impossibile caricare questi progressi.','Riprova','Nessuna sessione registrata.','Statistiche dettagliate','Il mio coach','Nutrizione','Altri programmi','Prossima sessione'],
  de: ['Mein aktuelles Programm','Mit jeder Einheit kommst du voran.','Training starten','Training fortsetzen','Abgeschlossene Einheiten','Dein Coach bereitet die nächste Phase vor. Deine Ergebnisse bleiben verfügbar.','Meine Fortschritte','Jede Einheit zählt. Hier findest du deinen Verlauf und deine Ergebnisse.','Abgeschlossene Programme','Einheiten und Ergebnisse','Ansehen','Dein nächster Schritt','Bereit','Programm abgeschlossen!','Einheit gespeichert!','Zur Startseite','Mein Programm','Woche','In Bearbeitung','Fortschritte konnten nicht geladen werden.','Erneut versuchen','Noch keine Einheiten gespeichert.','Detaillierte Statistiken','Mein Coach','Ernährung','Weitere Programme','Nächste Einheit'],
  ru: ['Моя текущая программа','Каждая тренировка — шаг вперёд.','Начать тренировку','Продолжить тренировку','Завершённые тренировки','Тренер готовит следующий этап. Ваши результаты остаются доступны.','Мой прогресс','Каждая тренировка важна. Ваш путь и результаты.','Завершённые программы','Тренировки и результаты','Открыть','Следующий этап','Готово','Программа завершена!','Тренировка сохранена!','На главную','Моя программа','Неделя','В процессе','Не удалось загрузить прогресс.','Повторить','Пока нет записанных тренировок.','Подробная статистика','Мой тренер','Питание','Другие программы','Следующая тренировка'],
  ar: ['برنامجي الحالي','تتقدم مع كل حصة تدريبية.','بدء حصتي','متابعة حصتي','الحصص المكتملة','يجهز مدربك المرحلة التالية. تبقى نتائجك متاحة.','تقدمي','كل حصة مهمة. اطلع على مسارك ونتائجك.','البرامج المكتملة','الحصص والنتائج','عرض','خطوتك التالية','جاهز','اكتمل البرنامج!','تم حفظ الحصة!','العودة للرئيسية','برنامجي','الأسبوع','قيد التنفيذ','تعذر تحميل التقدم.','إعادة المحاولة','لم تسجل أي حصة بعد.','إحصائيات مفصلة','مدربي','التغذية','برامج أخرى','الحصة التالية'],
};
export const clientJourneyTranslations = Object.fromEntries(Object.entries(values).map(([lang,labels]) => [lang,Object.fromEntries(keys.map((key,index) => [key,labels[index]]))]));
export const journeyLabels = language => clientJourneyTranslations[String(language || 'fr').split('-')[0]] || clientJourneyTranslations.fr;
