const rows = {
  fr: ['Votre mesure','En dessous','Zone de référence','Au-dessus','Nettement au-dessus','Âge au relevé','Homme','Femme','ans','Repères indicatifs, pas un objectif esthétique. Les seuils ne constituent pas un diagnostic et la méthode de mesure peut modifier le résultat.','Pas de zone personnalisée : âge ou sexe manquant, ou profil hors du champ de ces repères adultes.','Pas de seuil universel fiable pour cette donnée. Comparez vos mesures avec le même appareil et dans des conditions similaires.','Premier relevé affiché','Dernier relevé affiché','Évolution','Âge','Repères adultes généraux, sans seuil spécifique par âge.'],
  en: ['Your reading','Below','Reference range','Above','Well above','Age at reading','Male','Female','years','Indicative references, not aesthetic targets. Thresholds are not a diagnosis and the measurement method may affect the result.','No personal range: age or sex is missing, or the profile is outside these adult references.','No reliable universal threshold for this metric. Compare readings using the same device under similar conditions.','First displayed reading','Last displayed reading','Change','Age','General adult references, without age-specific thresholds.'],
  es: ['Tu medición','Por debajo','Zona de referencia','Por encima','Muy por encima','Edad al medir','Hombre','Mujer','años','Referencias orientativas, no objetivos estéticos. Los umbrales no son un diagnóstico y el método puede afectar al resultado.','Sin zona personal: falta edad o sexo, o el perfil queda fuera de estas referencias adultas.','No hay umbral universal fiable para este dato. Compara con el mismo aparato en condiciones similares.','Primera medición mostrada','Última medición mostrada','Evolución','Edad','Referencias adultas generales, sin umbrales específicos por edad.'],
  it: ['La tua misura','Sotto','Intervallo di riferimento','Sopra','Molto sopra','Età alla misura','Uomo','Donna','anni','Riferimenti indicativi, non obiettivi estetici. Le soglie non sono una diagnosi e il metodo può influire sul risultato.','Nessun intervallo personale: mancano età o sesso, oppure il profilo non rientra nei riferimenti adulti.','Nessuna soglia universale affidabile per questo dato. Confronta con lo stesso dispositivo in condizioni simili.','Prima misura mostrata','Ultima misura mostrata','Variazione','Età','Riferimenti adulti generali, senza soglie specifiche per età.'],
  de: ['Dein Messwert','Darunter','Referenzbereich','Darüber','Deutlich darüber','Alter bei Messung','Mann','Frau','Jahre','Orientierungswerte, keine ästhetischen Ziele. Grenzwerte sind keine Diagnose; die Messmethode kann das Ergebnis beeinflussen.','Kein persönlicher Bereich: Alter oder Geschlecht fehlen oder das Profil liegt außerhalb dieser Erwachsenenreferenzen.','Kein verlässlicher universeller Grenzwert für diesen Wert. Mit demselben Gerät unter ähnlichen Bedingungen vergleichen.','Erster angezeigter Wert','Letzter angezeigter Wert','Veränderung','Alter','Allgemeine Erwachsenenreferenzen ohne altersspezifische Grenzwerte.'],
  ru: ['Ваш результат','Ниже','Референсный диапазон','Выше','Значительно выше','Возраст при измерении','Мужчина','Женщина','лет','Приблизительные ориентиры, не эстетические цели. Пороги не являются диагнозом; метод измерения влияет на результат.','Нет личного диапазона: неизвестны возраст или пол либо профиль вне этих ориентиров для взрослых.','Для этого показателя нет надёжного универсального порога. Сравнивайте одним прибором в похожих условиях.','Первое показанное измерение','Последнее показанное измерение','Изменение','Возраст','Общие ориентиры для взрослых без возрастных порогов.'],
  ar: ['قياسك','أقل','النطاق المرجعي','أعلى','أعلى بكثير','العمر عند القياس','رجل','امرأة','سنة','مراجع إرشادية وليست أهدافًا جمالية. الحدود ليست تشخيصًا وقد تؤثر طريقة القياس في النتيجة.','لا يوجد نطاق شخصي: العمر أو الجنس غير معروف أو الحالة خارج هذه المراجع للبالغين.','لا يوجد حد عالمي موثوق لهذا القياس. قارن بالجهاز نفسه وفي ظروف متشابهة.','أول قياس معروض','آخر قياس معروض','التغير','العمر','مراجع عامة للبالغين دون حدود خاصة بالعمر.'],
};
export function referenceLabels(language) {
  return rows[String(language || 'fr').split('-')[0]] || rows.fr;
}
