import i18n from "../i18n/index";

export const DEFAULT_NUTRITION_ADVICE_SHEETS = [
  {
    id: "base-alimentation",
    title: "Bases de l'alimentation",
    category: "Éducation alimentaire",
    accent: "#111827",
    tags: ["structure", "repas", "repères"],
    summary: "Repères simples pour comprendre comment construire une journée alimentaire cohérente.",
    keyPoints: [
      "Un repas principal équilibré associe idéalement une source de protéines, des légumes, une portion de féculents et une matière grasse dosée.",
      "Les légumes apportent volume, fibres, micronutriments et satiété; ils peuvent être crus ou cuits selon la tolérance digestive.",
      "Les féculents ne sont pas interdits: ils servent surtout à couvrir énergie, entraînement, concentration et récupération.",
      "Les protéines aident la satiété, la masse musculaire, la récupération et la stabilité de la journée.",
      "Les matières grasses sont nécessaires, mais leur quantité est vite énergétique: l'huile, le beurre, les oléagineux et les sauces doivent être portionnés.",
      "La régularité compte plus que la perfection: une structure simple aide à éviter les compensations et les grignotages subis.",
    ],
    practicalTips: [
      "Commencer par stabiliser les repas principaux avant de modifier tous les détails.",
      "Visualiser l'assiette: 1/2 légumes, 1/4 protéine, 1/4 féculent, puis matière grasse mesurée.",
      "Adapter la portion de féculents selon faim, activité physique, objectif et évolution du poids.",
      "Prévoir 2 ou 3 repas faciles de secours pour les journées chargées.",
    ],
  },
  {
    id: "equivalences",
    title: "Équivalences alimentaires",
    category: "Éducation alimentaire",
    accent: "#0F766E",
    tags: ["portions", "autonomie", "substitutions"],
    summary: "Repères pour remplacer un aliment par un autre du même groupe sans déséquilibrer la ration.",
    keyPoints: [
      "Laitages: 125 g de yaourt nature, 100 g de fromage blanc, 2 petits-suisses nature ou 30 g de fromage peuvent représenter une portion selon l'objectif.",
      "Pain et féculents: environ 40 g de pain peuvent remplacer 100 g de féculents cuits; 60 g de pain remplacent environ 150 g de féculents cuits.",
      "Féculents cuits: 150 à 180 g de riz, pâtes, semoule, blé, quinoa ou pommes de terre correspondent souvent à une portion standard.",
      "Féculents crus: 50 à 60 g de pâtes/riz/semoule crus donnent environ 150 à 180 g cuits selon cuisson.",
      "Légumineuses: 150 g cuits de lentilles, pois chiches ou haricots peuvent remplacer une portion de féculents et apporter aussi des protéines.",
      "Matières grasses: 10 g d'huile, 10 g de beurre/margarine ou 15 g d'oléagineux représentent une portion de lipides.",
      "Fruits: 1 pomme, 1 poire, 1 orange, 2 kiwis, 150 g de fruits rouges ou 150 g de compote sans sucres ajoutés représentent souvent une portion.",
      "Viandes/poissons/oeufs: 100 à 120 g de viande/poisson, 2 oeufs ou 150 g de tofu peuvent représenter une portion protéique selon le contexte.",
      "Fromage: quand du fromage est prévu, il est souvent plus lisible de l'associer à du pain et de réduire les féculents du repas.",
      "Changer d'aliment dans le même groupe aide à garder l'adhérence sans modifier toute la ration.",
    ],
    practicalTips: [
      "Choisir une équivalence dans le même groupe alimentaire avant de modifier les quantités totales.",
      "Si on ajoute du pain au repas, réduire la portion de riz, pâtes, semoule ou pommes de terre.",
      "Si le fromage remplace un yaourt, surveiller davantage les lipides et le sel.",
      "Garder la quantité indiquée au départ, puis ajuster selon faim, digestion, objectif et évolution.",
      "Préparer une liste personnelle de 3 équivalences préférées par groupe pour faciliter les courses.",
      "En diabète, vérifier l'impact des équivalences glucidiques avec le contexte du repas, pas seulement le poids.",
    ],
  },
  {
    id: "hydration",
    title: "Hydratation",
    category: "Hydratation",
    accent: "#2563EB",
    tags: ["eau", "sport", "récupération"],
    summary: "Repères simples pour répartir l'eau sur la journée et adapter les apports autour de l'effort.",
    keyPoints: [
      "Viser en général 1,5 à 2 L d'eau par jour, à individualiser selon chaleur, transpiration et activité.",
      "Boire régulièrement fonctionne mieux que compenser avec de grands volumes d'un coup.",
      "Pendant un effort court ou modéré, l'eau suffit le plus souvent.",
      "Après un effort long, intense ou très transpirant, penser à l'eau minéralisée et aux apports en sodium.",
      "Les boissons sucrées ne sont pas une boisson d'hydratation quotidienne.",
      "En insuffisance rénale, insuffisance cardiaque ou consigne médicale, suivre la restriction hydrique prescrite.",
    ],
    practicalTips: [
      "Installer un repère visuel: bouteille graduée, gourde au bureau ou verre à chaque repas.",
      "Répartir: 1 à 2 verres au réveil, puis petites prises matin/après-midi.",
      "Ajouter citron, menthe, concombre ou fruits rouges si l'eau nature est difficile.",
      "Surveiller couleur des urines, maux de tête, fatigue et crampes comme signaux de terrain.",
    ],
  },
  {
    id: "indice-glycemique",
    title: "Indice glycémique",
    category: "Équilibre glucidique",
    accent: "#7C3AED",
    tags: ["IG", "diabète", "satiété"],
    summary: "Aide à choisir et associer les glucides pour une glycémie plus stable et une meilleure satiété.",
    keyPoints: [
      "L'indice glycémique dépend de l'aliment, mais aussi de la cuisson, du broyage et de l'association au repas.",
      "Les fibres, protéines et matières grasses ralentissent souvent l'absorption des glucides.",
      "Les jus, boissons sucrées et produits très raffinés montent plus vite que les aliments entiers.",
      "Les féculents très cuits ou mixés peuvent avoir un impact plus rapide qu'une version al dente ou entière.",
      "En diabète, le fruit est préférable entier, en portion, et rarement isolé.",
      "Le contexte du repas compte davantage qu'un classement IG appris par coeur.",
    ],
    practicalTips: [
      "Associer féculent + légumes + protéine plutôt que féculent seul.",
      "Privilégier pain complet, légumineuses, flocons d'avoine, riz complet ou pâtes al dente si tolérés.",
      "Limiter les boissons sucrées hors situation d'hypoglycémie.",
      "Tester les réponses individuelles avec les glycémies capillaires ou capteurs si le patient en dispose.",
    ],
  },
  {
    id: "sans-gluten",
    title: "Régime sans gluten",
    category: "Régime spécifique",
    accent: "#6D28D9",
    tags: ["sans gluten", "étiquettes", "contamination"],
    summary: "Repères pratiques pour retirer le gluten tout en gardant une alimentation structurée.",
    keyPoints: [
      "Le gluten est présent dans le blé, l'orge, le seigle, l'épeautre et leurs dérivés.",
      "La mention bio, artisanal ou complet ne signifie pas sans gluten.",
      "Les aliments naturellement sans gluten: riz, maïs, quinoa, sarrasin, millet, pommes de terre, légumineuses.",
      "Les produits transformés peuvent contenir du gluten caché: sauces, panures, charcuteries, plats préparés.",
      "En maladie coeliaque, la contamination croisée est un vrai sujet.",
      "Les produits sans gluten industriels peuvent être plus pauvres en fibres et plus riches en sucres ou graisses.",
    ],
    practicalTips: [
      "Lire la liste d'ingrédients et rechercher la mention sans gluten si nécessaire.",
      "Séparer grille-pain, planche, passoire et contenants si la sensibilité est forte.",
      "Varier les féculents sans gluten au lieu de remplacer uniquement par pain/pâtes sans gluten.",
      "Surveiller fibres, fer, magnésium et satiété lors du suivi.",
    ],
  },
  {
    id: "sans-lactose",
    title: "Régime sans lactose",
    category: "Régime spécifique",
    accent: "#0891B2",
    tags: ["sans lactose", "digestion", "calcium"],
    summary: "Aide à limiter le lactose sans perdre les repères en protéines, calcium et plaisir alimentaire.",
    keyPoints: [
      "L'intolérance au lactose dépend souvent de la dose et de la tolérance individuelle.",
      "Les yaourts et fromages affinés peuvent parfois être mieux tolérés que le lait.",
      "Les boissons végétales ne se valent pas: certaines sont pauvres en protéines ou non enrichies en calcium.",
      "Le lactose peut être présent dans desserts, biscuits, plats préparés, sauces et compléments.",
      "Supprimer tous les produits laitiers n'est pas toujours nécessaire si la tolérance permet des choix ciblés.",
      "Le calcium doit rester surveillé, surtout chez les femmes enceintes, allaitantes, seniors ou sportifs.",
    ],
    practicalTips: [
      "Tester progressivement: lait sans lactose, yaourt, fromage affiné, alternatives enrichies.",
      "Choisir de préférence des alternatives enrichies en calcium et vitamine D.",
      "Garder une source protéique si un laitage est retiré du repas.",
      "Noter symptômes, dose et contexte pour éviter les exclusions trop larges.",
    ],
  },
  {
    id: "diabete",
    title: "Diabète et équilibre glucidique",
    category: "Pathologie",
    accent: "#DC2626",
    tags: ["diabète", "glucides", "fibres"],
    summary: "Repères pour sécuriser les glucides, éviter les pics et garder une ration réaliste.",
    keyPoints: [
      "Éviter les boissons sucrées au quotidien, sauf conduite spécifique en cas d'hypoglycémie.",
      "Limiter les fruits à des portions cohérentes et les associer au repas ou à une source de fibres/protéines.",
      "Répartir les féculents sur la journée selon la ration validée.",
      "Privilégier les aliments riches en fibres si la digestion le permet.",
      "Les produits sucrés doivent rester exceptionnels et intégrés dans la stratégie globale.",
      "Les symptômes, traitements et horaires d'activité peuvent modifier les besoins.",
    ],
    practicalTips: [
      "Construire chaque repas autour de légumes + protéine + féculent dosé.",
      "Préférer fruit entier à jus ou compote sucrée.",
      "Éviter fruit seul en collation si la glycémie est instable.",
      "Prévoir une conduite claire pour l'hypoglycémie avec l'équipe médicale si besoin.",
    ],
  },
  {
    id: "hypertension",
    title: "Hypertension et sel",
    category: "Pathologie",
    accent: "#1D4ED8",
    tags: ["HTA", "sodium", "cardio"],
    summary: "Repères pour réduire le sodium sans rendre l'alimentation triste ou difficile à suivre.",
    keyPoints: [
      "Le sel visible n'est qu'une partie du sodium quotidien.",
      "Pain, fromages, charcuteries, plats préparés, bouillons et sauces sont souvent des sources importantes.",
      "Les herbes, épices, ail, oignon, citron et vinaigre aident à garder du goût.",
      "Les eaux très minéralisées en sodium ne sont pas adaptées à tous les profils hypertendus.",
      "La réduction doit rester progressive pour améliorer l'adhérence.",
      "En traitement médical, ne pas utiliser de sel de substitution riche en potassium sans avis médical.",
    ],
    practicalTips: [
      "Comparer les étiquettes sur pain, plats préparés et sauces.",
      "Limiter charcuteries et fromages salés dans la semaine.",
      "Goûter avant de resaler.",
      "Construire une liste d'assaisonnements aromatiques préférés.",
    ],
  },
  {
    id: "hypercholesterolemie",
    title: "Hypercholestérolémie",
    category: "Pathologie",
    accent: "#EA580C",
    tags: ["cholestérol", "matières grasses", "fibres"],
    summary: "Repères pour améliorer la qualité des graisses et augmenter les fibres utiles.",
    keyPoints: [
      "Limiter beurre, crème, charcuteries, fritures et produits ultra-transformés.",
      "Privilégier huiles végétales, noix/graines en portion adaptée et poissons selon les goûts.",
      "Les fibres solubles sont intéressantes: avoine, légumineuses, fruits, légumes.",
      "La perte de poids, l'activité physique et l'arrêt du tabac peuvent renforcer l'effet alimentaire.",
      "Les oeufs ne sont pas à supprimer systématiquement, mais leur fréquence doit rester cohérente.",
      "La qualité globale du repas compte autant que l'aliment isolé.",
    ],
    practicalTips: [
      "Utiliser huile d'olive ou colza en quantité maîtrisée.",
      "Mettre une portion de légumes à chaque repas principal.",
      "Remplacer une partie des protéines grasses par poisson, volaille, légumineuses ou tofu selon profil.",
      "Surveiller fibres et digestion lors des augmentations progressives.",
    ],
  },
  {
    id: "digestif-rgo-fodmap",
    title: "Troubles digestifs, RGO et FODMAP",
    category: "Pathologie",
    accent: "#9333EA",
    tags: ["digestion", "RGO", "FODMAP"],
    summary: "Repères pour ajuster volumes, textures et aliments irritants sans exclure trop vite.",
    keyPoints: [
      "Les symptômes digestifs dépendent souvent de la dose, du stress, du sommeil et de la vitesse du repas.",
      "En RGO, les gros repas, l'alcool, les repas tardifs et les aliments gras peuvent majorer l'inconfort.",
      "Les FODMAP doivent idéalement être travaillés par phase, pas supprimés au hasard.",
      "Les crudités, légumineuses et produits très fibreux peuvent nécessiter une progression.",
      "Les textures cuites, tendres ou fractionnées sont parfois mieux tolérées.",
      "Une restriction trop large peut réduire fibres, calcium, fer et plaisir alimentaire.",
    ],
    practicalTips: [
      "Noter symptômes, repas, heure, stress et sommeil pendant 7 à 14 jours.",
      "Tester cuisson, épluchage, mixage ou petites portions avant suppression complète.",
      "Éviter de s'allonger juste après le repas en RGO.",
      "Réintroduire progressivement pour identifier la vraie tolérance.",
    ],
  },
  {
    id: "renal",
    title: "Surveillance rénale",
    category: "Pathologie",
    accent: "#475569",
    tags: ["rein", "potassium", "phosphore"],
    summary: "Repères de prudence pour les profils rénaux, à adapter impérativement au stade et aux bilans biologiques.",
    keyPoints: [
      "Les besoins en protéines, potassium, phosphore, sodium et eau dépendent du stade rénal.",
      "Les consignes doivent suivre les bilans biologiques et l'avis médical.",
      "Les eaux, sels de substitution, compléments et protéines en poudre peuvent poser problème.",
      "Certains végétaux riches en potassium ne sont pas interdits pour tous, mais doivent être contextualisés.",
      "Les aliments ultra-transformés apportent souvent sodium et phosphates ajoutés.",
      "La ration doit rester individualisée, surtout en dialyse ou insuffisance rénale avancée.",
    ],
    practicalTips: [
      "Vérifier les dernières consignes médicales avant de modifier protéines ou potassium.",
      "Limiter les produits très transformés et bouillons/sauces salées.",
      "Ne pas ajouter de complément sans validation.",
      "Noter les apports hydriques si une restriction est prescrite.",
    ],
  },
  {
    id: "vegetarien-vegan",
    title: "Végétarien / végan",
    category: "Régime spécifique",
    accent: "#16A34A",
    tags: ["végétarien", "végan", "protéines"],
    summary: "Repères pour couvrir protéines et micronutriments dans une alimentation végétale.",
    keyPoints: [
      "Les protéines doivent être réparties sur la journée, pas concentrées sur un seul repas.",
      "Légumineuses, tofu, tempeh, soja, céréales et oléagineux se combinent selon tolérance.",
      "En végan strict, la vitamine B12 doit être supplémentée.",
      "Fer, zinc, calcium, iode, oméga-3 et vitamine D méritent une attention particulière.",
      "Les alternatives végétales ne sont pas toutes riches en protéines.",
      "Les volumes alimentaires peuvent devenir élevés si les protéines sont mal réparties.",
    ],
    practicalTips: [
      "Prévoir une source protéique identifiée à chaque repas principal.",
      "Choisir boissons ou yaourts végétaux enrichis en calcium si utilisés.",
      "Associer vitamine C et sources de fer végétal.",
      "Surveiller satiété, digestion et apports réels après quelques semaines.",
    ],
  },
  {
    id: "grossesse-allaitement",
    title: "Grossesse et allaitement",
    category: "Situation spécifique",
    accent: "#DB2777",
    tags: ["grossesse", "allaitement", "sécurité"],
    summary: "Repères de sécurité et de couverture des besoins pendant grossesse ou allaitement.",
    keyPoints: [
      "Les besoins évoluent selon trimestre, poids, activité, appétit et symptômes.",
      "Folate, fer, iode, calcium, vitamine D et oméga-3 sont des points de vigilance fréquents.",
      "Éviter alcool et produits à risque microbiologique selon recommandations médicales.",
      "Poissons: viser une bonne qualité en évitant les espèces trop riches en mercure.",
      "En allaitement, hydratation, énergie et régularité alimentaire comptent beaucoup.",
      "Les compléments doivent être validés par le professionnel de santé référent.",
    ],
    practicalTips: [
      "Fractionner si nausées, reflux ou satiété rapide.",
      "Garder une source protéique à chaque repas.",
      "Prévoir des collations simples si les besoins augmentent.",
      "Adapter les conseils aux bilans sanguins et au suivi médical.",
    ],
  },
  {
    id: "perte-poids",
    title: "Perte de poids",
    category: "Objectif",
    accent: "#0EA5E9",
    tags: ["déficit", "satiété", "adhérence"],
    summary: "Repères pour créer un déficit réaliste sans sacrifier la satiété ni la qualité alimentaire.",
    keyPoints: [
      "Le déficit doit rester soutenable et compatible avec activité, sommeil et faim.",
      "Les protéines et légumes aident souvent la satiété.",
      "Les féculents ne sont pas interdits: leur quantité et leur timing sont ajustés.",
      "Les matières grasses sont utiles mais doivent être portionnées.",
      "Les boissons sucrées et grignotages liquides peuvent peser lourd sans rassasier.",
      "L'adhérence compte plus qu'une journée parfaite isolée.",
    ],
    practicalTips: [
      "Repérer les repas où la faim est la plus forte avant de réduire.",
      "Garder une structure stable: petit-déjeuner si utile, repas principaux complets.",
      "Prévoir des alternatives simples pour restaurants, week-end et imprévus.",
      "Suivre tour de taille, énergie, faim et performances, pas uniquement le poids.",
    ],
  },
  {
    id: "prise-masse-sport",
    title: "Prise de masse et performance",
    category: "Objectif",
    accent: "#CA8A04",
    tags: ["sport", "prise de masse", "récupération"],
    summary: "Repères pour augmenter les apports sans rendre les repas irréalistes.",
    keyPoints: [
      "L'excédent énergétique doit être progressif pour limiter la prise de gras inutile.",
      "Les glucides soutiennent l'entraînement, les protéines soutiennent la récupération.",
      "Les lipides aident à densifier les repas mais ne doivent pas remplacer toute la qualité alimentaire.",
      "Le timing autour de l'entraînement peut aider si les séances sont intenses ou fréquentes.",
      "Les collations liquides ou semi-liquides peuvent aider si l'appétit est faible.",
      "Le sommeil reste un facteur majeur de progression.",
    ],
    practicalTips: [
      "Ajouter d'abord une collation simple avant de gonfler les repas principaux.",
      "Associer féculent + protéine dans le repas post-entraînement.",
      "Utiliser flocons, muesli, fruits, laitages ou alternatives végétales selon tolérance.",
      "Réévaluer poids, mensurations et performance toutes les 2 à 4 semaines.",
    ],
  },
  {
    id: "proteines-sport",
    title: "Compléments protéiques du sportif",
    category: "Supplémentation sportive",
    accent: "#111827",
    tags: ["whey", "gainer", "protéines"],
    summary: "Repères pour choisir une protéine en poudre ou un gainer sans remplacer la vraie ration.",
    keyPoints: [
      "La whey sert surtout à compléter un apport protéique insuffisant ou difficile à atteindre avec les repas.",
      "La whey concentrée contient souvent un peu plus de lactose; l'isolat est généralement plus filtré et mieux toléré en cas de sensibilité.",
      "La caséine est plus lente à digérer et peut être utile en collation longue, mais n'est pas obligatoire.",
      "Les protéines végétales peuvent convenir en végétarien/végan, à condition de vérifier la dose réelle de protéines par portion.",
      "Un gainer apporte protéines + glucides + calories: il est utile surtout si l'appétit est trop faible en prise de masse.",
      "Les shakers ne doivent pas remplacer systématiquement les repas complets: ils complètent une stratégie alimentaire.",
    ],
    practicalTips: [
      "Dose courante: 20 à 30 g de protéines par prise, à ajuster selon le total journalier visé.",
      "Moment: après entraînement, en collation ou au petit-déjeuner si cela aide à atteindre la cible protéique.",
      "Pour une prise de masse, commencer par augmenter la ration alimentaire avant d'ajouter un gainer très calorique.",
      "En intolérance lactose, préférer isolat, hydrolysat ou protéine végétale adaptée.",
      "Vérifier ingrédients, édulcorants, digestibilité et certification antidopage si compétition.",
      "Éviter en cas de pathologie rénale sans validation médicale.",
    ],
  },
  {
    id: "creatine",
    title: "Créatine",
    category: "Supplémentation sportive",
    accent: "#111827",
    tags: ["créatine", "force", "puissance"],
    summary: "Repères d'utilisation de la créatine monohydrate pour force, puissance et récupération.",
    keyPoints: [
      "La créatine monohydrate est la forme la plus étudiée et généralement la plus pertinente.",
      "Elle peut aider les efforts répétés, la force, la puissance et parfois la prise de masse maigre.",
      "Elle ne remplace ni l'entraînement, ni les apports énergétiques, ni le sommeil.",
      "Une légère prise de poids liée à l'eau intracellulaire est possible.",
      "La phase de charge n'est pas obligatoire.",
      "La prudence est nécessaire en pathologie rénale ou traitement médical.",
    ],
    practicalTips: [
      "Dose simple: 3 à 5 g par jour, tous les jours.",
      "Moment: le plus important est la régularité; autour d'un repas ou après entraînement si cela facilite l'habitude.",
      "Boire suffisamment et éviter de multiplier les produits contenant déjà de la créatine.",
      "Choisir créatine monohydrate pure, idéalement testée/certifiée si compétition.",
    ],
  },
  {
    id: "bcaa-eaa",
    title: "BCAA / EAA",
    category: "Supplémentation sportive",
    accent: "#111827",
    tags: ["BCAA", "EAA", "récupération"],
    summary: "Repères pour comprendre l'intérêt réel des acides aminés autour de l'entraînement.",
    keyPoints: [
      "Les BCAA seuls sont rarement utiles si l'apport protéique total est déjà suffisant.",
      "Les EAA sont plus complets que les BCAA, mais restent secondaires face aux protéines alimentaires.",
      "Ils peuvent avoir un intérêt ponctuel si l'entraînement se fait à jeun ou si l'apport protéique est très bas.",
      "Ils ne compensent pas une ration insuffisante en calories ou en protéines.",
      "Le marketing surestime souvent leur impact sur la récupération.",
      "En pratique, un repas ou une whey bien placée est souvent plus efficace et plus simple.",
    ],
    practicalTips: [
      "Priorité: atteindre la cible de protéines journalières avant d'ajouter BCAA/EAA.",
      "Si utilisés: suivre la dose du produit, souvent 5 à 10 g autour de l'entraînement.",
      "Éviter les versions très sucrées ou riches en stimulants si ce n'est pas recherché.",
      "Réserver aux cas où manger ou boire une protéine complète est difficile.",
    ],
  },
  {
    id: "citrulline",
    title: "Citrulline",
    category: "Supplémentation sportive",
    accent: "#111827",
    tags: ["citrulline", "performance", "pump"],
    summary: "Repères pour les sports de force, séances intenses et recherche de congestion musculaire.",
    keyPoints: [
      "La citrulline peut soutenir la production d'oxyde nitrique et la sensation de congestion.",
      "Elle est surtout utilisée avant les séances de musculation ou efforts intenses.",
      "L'effet dépend de la dose, de la régularité et de la tolérance digestive.",
      "Elle ne remplace pas les glucides, l'hydratation ou l'échauffement.",
      "Elle peut être présente dans des pre-workouts avec caféine et autres actifs.",
      "Prudence en cas de traitement cardiovasculaire ou tension instable.",
    ],
    practicalTips: [
      "Dose courante: 6 à 8 g de L-citrulline ou citrulline malate environ 30 à 60 min avant séance.",
      "Commencer plus bas si digestion sensible.",
      "Éviter de cumuler plusieurs pre-workouts sans vérifier les doses totales.",
      "Tester à l'entraînement, jamais pour la première fois le jour d'une compétition.",
    ],
  },
  {
    id: "l-carnitine",
    title: "L-carnitine",
    category: "Supplémentation sportive",
    accent: "#111827",
    tags: ["L-carnitine", "perte de poids", "énergie"],
    summary: "Repères réalistes sur la L-carnitine, souvent vendue comme brûleur de graisse.",
    keyPoints: [
      "La L-carnitine n'est pas un brûleur de graisse magique.",
      "Son effet sur la perte de poids est généralement modeste et dépend surtout du déficit énergétique global.",
      "Elle peut avoir un intérêt dans certains contextes spécifiques, mais ce n'est pas une priorité.",
      "Sommeil, protéines, fibres, activité et régularité alimentaire ont souvent plus d'impact.",
      "Les produits minceur combinés peuvent contenir caféine ou stimulants.",
      "La tolérance digestive doit être surveillée.",
    ],
    practicalTips: [
      "Si utilisée: souvent 1 à 2 g par jour selon produit et tolérance.",
      "Ne pas l'utiliser comme justification pour réduire excessivement les apports.",
      "Vérifier les stimulants associés dans les formules minceur.",
      "Réévaluer l'intérêt après quelques semaines sur critères objectifs.",
    ],
  },
  {
    id: "fruits-legumes-saison",
    title: "Fruits et légumes de saison",
    category: "Saisonnalité",
    accent: "#15803D",
    tags: ["saison", "fibres", "micronutriments"],
    summary: "Repères pour augmenter variété, fibres et plaisir alimentaire grâce aux saisons.",
    keyPoints: [
      "La saisonnalité aide à varier les couleurs, textures et micronutriments.",
      "Les surgelés nature sont une bonne alternative hors saison.",
      "Crudités et cuidités n'ont pas la même tolérance digestive.",
      "Les fruits restent à portionner selon l'objectif et les pathologies.",
      "Les légumes peuvent être intégrés en soupe, poêlée, gratin léger, salade ou accompagnement.",
      "La variété compte autant que la quantité.",
    ],
    practicalTips: [
      "Choisir 2 légumes et 2 fruits de saison à tester chaque semaine.",
      "Alterner cru/cuit selon digestion.",
      "Préparer une base de légumes cuits pour 2 à 3 jours.",
      "Utiliser herbes, épices et citron pour éviter la monotonie.",
    ],
  },
  {
    id: "sommeil",
    title: "Améliorer le sommeil",
    category: "Hygiène de vie",
    accent: "#4338CA",
    tags: ["sommeil", "récupération", "rythme"],
    summary: "Repères nutritionnels et comportementaux pour soutenir le sommeil et la récupération.",
    keyPoints: [
      "Un dîner trop lourd, trop gras ou trop tardif peut perturber l'endormissement.",
      "La caféine peut rester active plusieurs heures selon les personnes.",
      "L'alcool dégrade souvent la qualité du sommeil malgré une somnolence initiale.",
      "Une restriction alimentaire trop forte peut augmenter faim nocturne ou réveils.",
      "Le rythme régulier des repas aide certains patients à stabiliser l'énergie.",
      "Hydratation excessive juste avant coucher peut augmenter les réveils nocturnes.",
    ],
    practicalTips: [
      "Tester une limite caféine en début/milieu d'après-midi.",
      "Prévoir un dîner digeste avec protéine, légumes et féculent adapté si faim nocturne.",
      "Éviter les grosses prises hydriques dans l'heure avant coucher.",
      "Noter sommeil, heure de dîner, alcool, caféine et entraînement pour repérer les liens.",
    ],
  },
  {
    id: "anti-age",
    title: "Alimentation anti-âge",
    category: "Prévention",
    accent: "#BE123C",
    tags: ["prévention", "antioxydants", "longévité"],
    summary: "Repères pour soutenir santé métabolique, masse musculaire et qualité alimentaire au fil du temps.",
    keyPoints: [
      "La priorité reste une alimentation régulière, riche en végétaux variés et protéines suffisantes.",
      "La masse musculaire se protège avec protéines, activité physique et récupération.",
      "Les fibres soutiennent microbiote, cholestérol et satiété.",
      "Les oméga-3, vitamine D, calcium et antioxydants peuvent être des points de vigilance.",
      "Les produits ultra-transformés, alcool excessif et sédentarité accélèrent souvent les déséquilibres.",
      "La prévention doit rester adaptée aux pathologies et traitements.",
    ],
    practicalTips: [
      "Mettre une source protéique à chaque repas principal.",
      "Varier les couleurs de végétaux dans la semaine.",
      "Intégrer poissons, noix/graines ou alternatives selon profil.",
      "Surveiller force, énergie, sommeil et digestion avec l'âge.",
    ],
  },
  {
    id: "complements",
    title: "Compléments alimentaires",
    category: "Supplémentation",
    accent: "#64748B",
    tags: ["compléments", "sécurité", "sport"],
    summary: "Repères pour utiliser les compléments seulement quand ils répondent à un besoin réel.",
    keyPoints: [
      "Un complément ne remplace pas une ration déséquilibrée.",
      "Les besoins doivent idéalement être objectivés: bilan biologique, symptômes, contexte sportif ou médical.",
      "Les interactions avec traitements existent, surtout plantes, minéraux et fortes doses.",
      "En grossesse, allaitement, pathologie rénale ou cardiaque, prudence renforcée.",
      "Protéines en poudre, créatine, vitamine D, oméga-3 ou magnésium ne sont pas utiles à tout le monde.",
      "La qualité du produit, le dosage et la durée comptent autant que le choix du complément.",
    ],
    practicalTips: [
      "Lister tous les compléments déjà pris avant d'en ajouter un.",
      "Vérifier objectif, dose, durée et critère d'arrêt.",
      "Privilégier les corrections alimentaires quand elles suffisent.",
      "Demander validation médicale en cas de traitement ou pathologie.",
    ],
  },
  {
    id: "tca",
    title: "Troubles du comportement alimentaire",
    category: "Pathologie",
    accent: "#BE185D",
    tags: ["TCA", "accompagnement", "sécurité"],
    summary: "Repères de prudence pour accompagner sans renforcer le contrôle ou la culpabilité.",
    keyPoints: [
      "La priorité est la sécurité, l'alliance thérapeutique et le travail pluridisciplinaire.",
      "Les objectifs chiffrés peuvent être sensibles et doivent être utilisés avec prudence.",
      "Les restrictions rigides peuvent aggraver compulsions, évitements ou anxiété alimentaire.",
      "La régularité alimentaire est souvent plus importante que la perfection nutritionnelle.",
      "Le vocabulaire moral autour des aliments est à éviter.",
      "Les signaux de gravité nécessitent une orientation médicale spécialisée.",
    ],
    practicalTips: [
      "Privilégier des repères simples et sécurisants plutôt qu'une liste d'interdits.",
      "Évaluer faim, satiété, émotions et contexte sans jugement.",
      "Ne pas imposer de pesées alimentaires si cela augmente l'anxiété.",
      "Travailler en lien avec médecin, psychologue ou psychiatre si besoin.",
    ],
  },
];

export function mergeAdviceSheets(customSheets = []) {
  const custom = Array.isArray(customSheets) ? customSheets : [];
  const seen = new Set();
  return [...DEFAULT_NUTRITION_ADVICE_SHEETS, ...custom].filter(
    (sheet) => sheet && sheet.id && !seen.has(sheet.id) && seen.add(sheet.id)
  );
}

export function getAdviceSheetPreview(sheet) {
  const baseKey = `auto.nutritionAdviceSheets.${sheet.id}`;
  const translateValue = (path, fallback) => i18n.t(`${baseKey}.${path}`, fallback);
  const translateList = (path, values = []) =>
    (values || []).map((value, index) => translateValue(`${path}.${index}`, value));

  return {
    id: sheet.id,
    title: translateValue("title", sheet.title),
    category: translateValue("category", sheet.category),
    accent: sheet.accent,
    tags: translateList("tags", sheet.tags || []),
    summary: translateValue("summary", sheet.summary),
    keyPoints: translateList("keyPoints", sheet.keyPoints || []),
    practicalTips: translateList("practicalTips", sheet.practicalTips || []),
  };
}
