import assert from 'node:assert/strict';
import { isClientProgram, asReusableTemplate, libraryLabels, programClientName, resolvePreparedClient } from '../src/utils/programLibrary.js';
assert.equal(programClientName({ firstName: 'Tom', lastName: 'MARIE' }), 'Tom MARIE');
const client = { id: 'c', name: 'Tom', trainingPlan: { cycles: [{ draftProgramId: 'old' }] } };
assert.equal(resolvePreparedClient({ id: 'old' }, [client]), client);
assert.equal(resolvePreparedClient({ preparedForClientId: 'c' }, [client]), client);
assert.equal(isClientProgram({ cycleDraft: true }), true);
assert.equal(isClientProgram({ cyclePreparation: {} }), true);
assert.equal(isClientProgram({ libraryKind: 'template', cycleDraft: true }), false);
assert.equal(isClientProgram({ name: 'Legacy programme' }), false);
const source = { name: 'Model', libraryKind: 'client', cycleDraft: true, preparedForClientId: 'client', assignedClients: ['client'], cyclePreparation: {}, sessionsEffectuees: [{ id: 'record' }], sessions: [{ exercises: [{ name: 'Squat', 'Charge (kg)': 40, 'Répétitions': 10, cyclePrescription: { recordId: 'private' }, sets: [{ chargeKg: 40, reps: 10 }] }] }] };
const before = JSON.stringify(source);
const template = asReusableTemplate(source);
assert.equal(isClientProgram(template), false);
assert.equal(template.preparedForClientId, undefined);
assert.equal(template.assignedClients, undefined);
assert.equal(template.sessionsEffectuees, undefined);
assert.equal(template.sessions[0].exercises[0].cyclePrescription, undefined);
assert.equal(template.sessions[0].exercises[0]['Charge (kg)'], 0);
assert.equal(template.sessions[0].exercises[0].sets[0].chargeKg, 0);
assert.equal(template.sessions[0].exercises[0]['Répétitions'], 10);
assert.equal(JSON.stringify(source), before);
for (const lang of ['fr', 'en', 'es', 'it', 'de', 'ru', 'ar']) assert.equal(libraryLabels[lang].length, 6);
console.log('Program library: legacy cycle classification, isolated reusable templates, preserved client history, seven languages OK');
