// Local demo emulator only; never loads production credentials or environment files.
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
assert.match(process.env.FIRESTORE_EMULATOR_HOST||'',/^(localhost|127\.0\.0\.1):\d+$/,'Local emulator required');
process.env.METADATA_SERVER_DETECTION='none';
const {initializeApp,deleteApp}=require('firebase-admin/app');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
const {createSubscriptionCycles,orientation,adaptSessions}=require('../backend/utils/subscriptionCycles');
const {advanceCompletedTrainingCycle}=require('../functions/trainingCycleCompletion');
const {createPaidProgramDelivery,paidProgramId}=require('../backend/utils/paidProgramOrders');
const app=initializeApp({projectId:'demo-byl-security'},randomUUID());
const db=getFirestore(app);
db.settings({host:process.env.FIRESTORE_EMULATOR_HOST,ssl:false});
const owned=[];
const receipts=[];
const timestamp=Date.now();
const options={sexe:'female',niveau:'beginner',objectif:'hypertrophy',nbSeances:2};
let generated=0;
const template={sessions:[{corps:[{id:'bench',nom:'Bench press',repetitions:10,series:3,charge:20}]},{corps:[{id:'row',nom:'Rowing',repetitions:10,series:3}]}]};
const service=createSubscriptionCycles({db,FieldValue,now:()=>timestamp,generateProgram:async args=>{assert.equal(args.prepareOnly,true);generated++;return structuredClone(template);}});
async function fixture(patch={}) {
  const ref=db.collection('clients').doc(`cycle_test_${randomUUID()}`);owned.push(ref);
  await ref.set({abonnementActif:true,stripeSubscriptionId:'sub_fixture',subscriptionAccessUntil:new Date(timestamp+86400000),...patch});
  return ref;
}
async function main(){
  assert.equal(orientation('Endurance musculaire'),'endurance');
  const ref=await fixture();
  const first=await service.enroll({clientRef:ref,options,uid:ref.id});
  assert.ok(first.programAssignmentId);
  let client=(await ref.get()).data();
  assert.equal(client.trainingPlan.cycles[0].type,'hypertrophy');
  assert.equal(client.trainingPlan.cycles[0].weeks,4);
  await service.enroll({clientRef:ref,options,uid:ref.id});
  assert.equal(generated,1,'renewal must not generate an extra programme');
  const program=ref.collection('programmes').doc(first.programAssignmentId);
  const count=p=>p.sessions.length*p.activeWeeks;
  for(let i=0;i<7;i++)await program.collection('sessionsEffectuees').doc(String(i)).set({status:'completed'});
  await program.collection('sessionsEffectuees').doc('partial').set({status:'completed',isPartial:true});
  assert.equal(await advanceCompletedTrainingCycle(db,ref.id,program.id,count),false);
  await program.collection('sessionsEffectuees').doc('7').set({status:'completed'});
  assert.equal(await advanceCompletedTrainingCycle(db,ref.id,program.id,count),true);
  assert.equal(await advanceCompletedTrainingCycle(db,ref.id,program.id,count),false);
  await Promise.all([service.process(ref.id),service.process(ref.id)]);
  client=(await ref.get()).data();
  const recovery=ref.collection('programmes').doc(client.currentProgramme);
  const recoveryData=(await recovery.get()).data();
  assert.equal(recoveryData.activeWeeks,1);
  assert.equal(recoveryData.sessions[0].corps[0].series,2);
  assert.equal(recoveryData.sessions[0].corps[0].id,'bench');
  assert.equal((await ref.collection('programmes').get()).size,2);
  for(let i=0;i<2;i++)await recovery.collection('sessionsEffectuees').doc(String(i)).set({status:'completed'});
  await advanceCompletedTrainingCycle(db,ref.id,recovery.id,count);
  await ref.update({abonnementActif:false});
  await service.process(ref.id);
  assert.equal((await ref.get()).data().currentProgramme,null);
  assert.equal((await ref.collection('programmes').get()).size,2,'cancellation blocks generation');
  await ref.update({abonnementActif:true});
  await service.enroll({clientRef:ref,options,uid:ref.id});
  assert.equal((await ref.collection('programmes').get()).size,3,'reactivation resumes at next cycle');
  const coachPlan={revision:9,cycles:[{id:'coach',type:'custom',weeks:2,programId:''}]};
  const coach=await fixture({trainingPlan:coachPlan});
  const coachResult=await service.enroll({clientRef:coach,options,uid:coach.id});
  assert.equal(coachResult.programAssignmentId,null);
  assert.deepEqual((await coach.get()).data().trainingPlan,coachPlan);
  const independent=await fixture({sportFollowView:'programs'});
  await service.enroll({clientRef:independent,options,uid:independent.id});
  assert.equal((await independent.get()).data().trainingPlan,undefined);
  const expired=await fixture({subscriptionAccessUntil:new Date(timestamp-1)});
  await assert.rejects(()=>service.enroll({clientRef:expired,options,uid:expired.id}),/subscription-not-active/);
  const existing=await fixture({currentProgramme:'existing'});
  await existing.collection('programmes').doc('existing').set({...template,origine:'auto',objectif:'force',activeWeeks:3});
  const adopted=await service.enroll({clientRef:existing,options,uid:existing.id});
  assert.equal(adopted.programAssignmentId,'existing','renewal adopts existing programme without losing progress');
  assert.equal((await existing.get()).data().trainingPlan.cycles[0].type,'strength');
  const looping=await fixture({subscriptionCycle:{enabled:true,options},trainingPlan:{revision:1,cycles:[{id:'first',type:'endurance',weeks:2,closedAt:'2026-09-01',name:'Coach custom name'}]}});
  await service.process(looping.id);
  const loop=(await looping.get()).data().trainingPlan.cycles;
  assert.equal(loop.length,2);
  assert.equal(loop[1].type,'endurance');
  assert.equal(loop[1].weeks,2);
  assert.equal(loop[1].name,'Coach custom name');
  const paid=await fixture({pending_program_prefs:options});
  const deliver=createPaidProgramDelivery({db,FieldValue,now:()=>timestamp,resolveClientRef:async()=>paid,fulfillSubscription:service.enroll,generateProgram:async()=>{throw new Error('legacy delivery must not run');}});
  const session={id:`cs_${randomUUID().replaceAll('-','')}`,mode:'subscription',status:'complete',payment_status:'paid',metadata:{firebaseUid:paid.id,audience:'particulier'}};
  receipts.push(paidProgramId(session.id));
  const delivered=await deliver({session,uid:paid.id});
  const replay=await deliver({session,uid:paid.id});
  assert.equal(replay.programAssignmentId,delivered.programAssignmentId);
  const invoice={...session,id:`in_${randomUUID().replaceAll('-','')}`};receipts.push(paidProgramId(invoice.id));
  const renewed=await deliver({session:invoice,uid:paid.id});
  assert.equal(renewed.programAssignmentId,delivered.programAssignmentId);
  assert.equal((await paid.collection('programmes').get()).size,1,'paid renewal uses the same timeline');
  const conflict=await fixture();
  const conflicting=createSubscriptionCycles({db,FieldValue,now:()=>timestamp,generateProgram:async()=>{
    await conflict.update({'trainingPlan.revision':99});return template;
  }});
  await assert.rejects(()=>conflicting.enroll({clientRef:conflict,options,uid:conflict.id}),/cycle-plan-changed/);
  assert.equal((await conflict.collection('programmes').get()).size,0,'changed coach plan prevents stale assignment');
  const adapted=adaptSessions(template.sessions,'recovery',[{status:'completed',completedAt:new Date(timestamp).toISOString(),exerciseSnapshots:[{exerciseId:'bench',sets:[{chargeKg:100,reps:10}]}]}]);
  assert.equal(adapted[0].corps[0].cyclePrescription.suggestedKg,60);
  assert.equal(adapted[0].corps[0].charge,0,'weight remains a suggestion');
  console.log('PASS subscription cycles: enrollment, renewal, validated sessions, short recovery, concurrency, cancellation, reactivation, coach ownership, expiry, revision conflict, load suggestions');
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{
  for(const ref of owned){await db.recursiveDelete(ref);await db.collection('subscription_cycle_jobs').doc(ref.id).delete();}
  for(const id of receipts)await db.collection('custom_program_orders').doc(id).delete();
  await deleteApp(app);
});
