import assert from 'node:assert/strict';
import { cycleSessionWeeks } from '../src/utils/cycleSessionWeeks.js';
const dates = ['2026-06-01', '2026-06-03', '2026-06-08', '2026-06-09', '2026-06-10', '2026-09-12', '2026-09-15'];
const records = dates.map((completedAt, id) => ({ id: String(id), completedAt, status: 'completed' }));
const original = JSON.stringify(records);
let result = cycleSessionWeeks([...records].reverse(), 2, 4);
assert.deepEqual(result.weeks.map(w => w.length), [2, 2, 2, 1]);
assert.equal(result.weeks[2][0].id, '4', 'third session in a calendar week advances the training week');
assert.equal(result.weeks[2][1].id, '5', 'resumption after a break finishes the pending week');
assert.equal(result.extra.length, 0, 'late sessions belong to training weeks');
assert.equal(JSON.stringify(records), original, 'real dates and records are untouched');
result = cycleSessionWeeks([...records, { id: 'partial', status: 'in_progress', completedAt: '2026-06-02' }], 2, 4);
assert.deepEqual(result.weeks.map(w => w.length), [2, 2, 2, 1]);
assert.equal(result.partial.length, 1);
result = cycleSessionWeeks([...records, { status: 'completed', completedAt: '2026-10-01' }, { status: 'completed', completedAt: '2026-10-03' }], 2, 4);
assert.deepEqual(result.weeks.map(w => w.length), [2, 2, 2, 2]);
assert.equal(result.extra.length, 1);
assert.equal(cycleSessionWeeks(records, 0, 4).extra.length, 7);
assert.equal(cycleSessionWeeks([{ status: 'done', id: 'undated' }], 2, 1).weeks[0][0].id, 'undated');
console.log('Sequential training weeks: pauses, extra frequency, partial attempts, overflow and date preservation OK');
