import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mergeConfirmedCalendarEvents } from '../src/utils/confirmedCalendarEvent.js';
const require = createRequire(import.meta.url);
const { serializeConfirmedSession } = require('../backend/utils/confirmedCalendarSession.js');
const start = new Date('2026-09-10T10:00:00.000Z'), end = new Date('2026-09-10T11:00:00.000Z');
const data = { clientId: 'client', clientName: 'Test', coachId: 'coach', programmeId: 'assigned', sessionIndex: 2, start: { toDate: () => start }, end: { toDate: () => end }, status: 'validée', visibility: 'both', title: 'Séance 3' };
const session = serializeConfirmedSession('confirmed', data);
const response = { ok: true, duplicate: true, session };
const previous = [{ id: 'unrelated', start }];
assert.equal(mergeConfirmedCalendarEvents(previous, [{ session }, { ok: false, session }, undefined], 'coach'), previous, 'no unconfirmed or failed write appears');
assert.equal(mergeConfirmedCalendarEvents(previous, [response], 'other-coach'), previous, 'scope cannot leak');
const result = mergeConfirmedCalendarEvents(previous, [response, response], 'coach');
assert.equal(result.length, 2, 'duplicate response is merged only once');
assert.deepEqual(result[1].start, start);
assert.equal(result[1].status, 'validée', 'existing duplicate retains server status');
assert.equal(result[1].programmeId, 'assigned');
assert.equal(mergeConfirmedCalendarEvents(result, [response], 'coach').length, 2);
assert.equal(mergeConfirmedCalendarEvents(previous, [{ ok: true, session: { ...session, start: null } }], 'coach'), previous);
console.log('Confirmed planning updates OK: acknowledgement, scope, actual dates/status, deduplication, invalid response.');
