import assert from 'node:assert/strict';
import { cycleExerciseEvidence } from '../src/utils/cycleEvidence.js';
import { varyCycleExercises } from '../src/utils/cycleVariation.js';
import { adaptCycleSessions } from '../src/utils/cyclePrescription.js';
import { buildCyclePreviews } from '../src/utils/cyclePreviews.js';
import { cycleDraft } from '../src/utils/trainingCycles.js';
const ex = { id: 'curl', nom: 'Curl', 'Répétitions': 10, 'Séries': 4, 'Charge (kg)': 20, 'Repos (min:sec)': 90, materiel: ['Haltères'], groupe_musculaire: 'Biceps' };
const result = (id, date, reps = 10, count = 4) => ({ id, completedAt: date, status: 'completed', exerciseSnapshots: [{ exerciseId: 'curl', sets: Array.from({length: count}, () => ({reps, chargeKg: 20})) }] });
const history = [result('a', '2026-10-01'), result('b', '2026-10-03')];
assert.equal(cycleExerciseEvidence(ex, history).repeatedSuccess, true);
assert.equal(cycleExerciseEvidence(ex, [history[0], history[0]]).repeatedSuccess, false);
assert.equal(cycleExerciseEvidence(ex, [...history, result('c', '2026-10-05', 7)]).repeatedSuccess, false);
assert.equal(cycleExerciseEvidence(ex, [...history, result('c', '2026-10-05', 10, 0)]).repeatedSuccess, false, 'empty latest snapshot must not be skipped');
assert.equal(cycleExerciseEvidence(ex, [history[0], result('c','2026-10-05',10,3)]).repeatedSuccess, false, 'all source sets required even if next cycle has fewer sets');
const bodyweight = {...ex, 'Charge (kg)': 0};
const zeroHistory = history.map(r => ({...r, exerciseSnapshots:[{exerciseId:'curl',sets:Array.from({length:4},()=>({reps:10,chargeKg:0}))}]}));
assert.equal(cycleExerciseEvidence(bodyweight, zeroHistory).repeatedSuccess, true);
const sessions = [{ exercises: [{...ex,id:'main',nom:'Repère'}, ex] }];
const bank = [{...ex, variantes:['Curl alterné']}, {...ex,id:'alternate',nom:'Curl alterné',niveau:'Débutant'}];
assert.equal(varyCycleExercises(sessions, bank, 'hypertrophy', history)[0].exercises[1].id, 'alternate');
assert.equal(varyCycleExercises(sessions, bank, 'hypertrophy', [])[0].exercises[1].id, 'curl');
assert.equal(varyCycleExercises(sessions, bank, 'recovery', history)[0].exercises[1].id, 'curl');
assert.equal(varyCycleExercises(sessions, bank, 'strength', history)[0].exercises[0].id, 'main');
const failed = adaptCycleSessions([{exercises:[ex]}], 'hypertrophy', [...history, result('c','2026-10-05',6)]).sessions[0].exercises[0];
assert.equal(failed.cyclePrescription.reason, 'consolidate');
assert.equal(failed['Répétitions'], 10);
const plan = {cycles:[{id:'old',programId:'source',type:'hypertrophy'},{id:'next',type:'hypertrophy',weeks:4}]};
const source = {id:'source',sessions,sessionsEffectuees:history,__detailsLoaded:true};
const preview = buildCyclePreviews(plan,[source],'next',bank).next;
const draft = cycleDraft({...source,sessions:varyCycleExercises(sessions,bank,'hypertrophy',history)},plan.cycles[1],'Test','coach',history);
assert.deepEqual(preview.sessions,draft.sessions,'preview and preparation share identical evidence/variation rules');
assert.equal(draft.sessions[0].exercises[1]['Charge (kg)'],0,'old load never transfers to new movement');
console.log('Result-based proposals: failures, incomplete/duplicate records, bodyweight, preserved anchors, gated variations and preview/draft parity passed.');

const oldVariant = [{exercises:[{...ex, cycleVariation:{previousName:'Old exercise',proposed:true}}]}];
assert.equal(varyCycleExercises(oldVariant, [], 'hypertrophy', [])[0].exercises[0].cycleVariation, undefined);
assert.equal(oldVariant[0].exercises[0].cycleVariation.previousName, 'Old exercise');
