import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { cycleTimeline, suggestedCycles, continuingCyclePlan, displayedCyclePlan, validateCyclePlan, cycleDraft, writeCyclePlan, historyWeek, formatCycleDate } from '../src/utils/trainingCycles.js';
import { cycleTranslations } from '../src/i18n/cycleTranslations.js';
let id = 0;
assert.equal(formatCycleDate('2026-09-11', 'fr'), '11/09/2026');
assert.equal(formatCycleDate('2027-01-03', 'fr-FR'), '03/01/2027');
assert.equal(formatCycleDate(null), '—');
assert.equal(formatCycleDate('invalid'), '—');
const plan = { start: '2026-09-11', cycles: suggestedCycles(() => String(++id)), revision: 0 };
const running = { id: 'running', name: 'Prise de masse', activeWeeks: 4, sessions: [{}], sessionsEffectuees: [{ status: 'validée' }], __detailsLoaded: true, assignedAt: '2026-09-01T12:00:00' };
const continuation = continuingCyclePlan({ currentProgramme: 'running' }, [running], plan);
assert.equal(continuation.cycles[0].programId, 'running');
assert.equal(continuation.cycles[0].type, 'hypertrophy');
assert.equal(continuation.cycles[1].type, 'recovery');
assert.equal(continuation.start, '2026-09-01');
assert.equal(continuation.cycles.reduce((sum, c) => sum + c.weeks, 0), 26);
assert.equal(running.sessionsEffectuees.length, 1, 'existing progress stays untouched');
assert.equal(continuingCyclePlan({}, [running, { ...running, id: 'another' }], plan), plan, 'ambiguous active programmes require coach choice');
assert.equal(continuingCyclePlan({}, [{ ...running, __detailsLoaded: false }], plan), plan, 'never infer from incomplete history');
assert.equal(continuingCyclePlan({}, [{ ...running, activeWeeks: 1 }], plan), plan, 'completed programme must not be restarted');
assert.equal(displayedCyclePlan(undefined, plan).cycles.length, 10, 'full proposal immediately visible');
assert.equal(displayedCyclePlan({ cycles: [], revision: 0 }, plan).cycles, plan.cycles, 'legacy empty drafts get the proposal');
const intentionallyEmpty = { start: plan.start, cycles: [], revision: 1 };
assert.equal(displayedCyclePlan(intentionallyEmpty, plan), intentionallyEmpty, 'saved coach choices are respected');
assert.equal(displayedCyclePlan(plan, { cycles: [] }), plan, 'existing nonempty plans are not replaced');
assert.equal(plan.cycles.reduce((sum, c) => sum + c.weeks, 0), 26);
assert.equal(validateCyclePlan(plan), plan);
const timeline = cycleTimeline(plan);
assert.equal(timeline[0].end, '2026-10-08');
assert.equal(timeline[1].start, '2026-10-09');
assert.deepEqual(cycleTimeline({ start: '' }), []);
assert.doesNotThrow(() => cycleTimeline({ ...plan, cycles: [{ weeks: NaN }] }));
assert.throws(() => validateCyclePlan({ ...plan, cycles: [{ ...plan.cycles[0], weeks: 0 }] }));
assert.throws(() => validateCyclePlan({ ...plan, cycles: plan.cycles.map(c => ({ ...c, programId: 'same' })) }));
const source = { sessions: [{ name: 'A', corps: [{ charge: 20 }] }], sessionsEffectuees: ['old'], completedSessions: 12 };
const draft = cycleDraft(source, plan.cycles[0], 'Next', 'coach');
assert.equal(draft.durationWeeks, 4);
assert.equal(draft.sessionsEffectuees, undefined);
assert.equal(draft.completedSessions, undefined);
assert.equal(draft.status, 'draft');
draft.sessions[0].corps[0].charge = 30;
assert.equal(source.sessions[0].corps[0].charge, 20);
assert.equal(draft.seances, undefined, 'do not duplicate the sessions payload');
assert.equal(historyWeek({ completedAt: '2026-09-18T12:00:00Z' }, plan.start), 2);
assert.equal(historyWeek({}, plan.start), null);
assert.throws(() => validateCyclePlan({ ...plan, start: '2026-02-31' }));
let stored = { trainingPlan: { ...plan } };
const writes = [];
const transaction = { get: async () => ({ exists: () => true, data: () => stored }), set: (...args) => writes.push(args), update: (...args) => writes.push(args) };
await writeCyclePlan(transaction, 'client', plan, async () => ({ ref: 'draft', data: draft }));
assert.equal(writes.length, 2);
assert.equal(writes[1][1].trainingPlan.revision, 1);
writes.length = 0;
stored.trainingPlan.revision = 3;
await assert.rejects(writeCyclePlan(transaction, 'client', plan), /conflict/);
assert.equal(writes.length, 0);
stored = { trainingPlan: { ...plan } };
await assert.rejects(writeCyclePlan(transaction, 'client', plan, async () => { throw new Error('missing-program'); }), /missing-program/);
assert.equal(writes.length, 0, 'a removed programme must not leave a saved cycle association');
stored = { trainingPlan: { ...plan, cycles: [{ ...plan.cycles[0], closedAt: '2026-09-11' }] } };
await assert.rejects(writeCyclePlan(transaction, 'client', { ...stored.trainingPlan, start: '2026-09-12' }), /closed-cycle/);
stored = { currentProgramme: 'old', trainingPlan: { ...plan, cycles: [{ ...plan.cycles[0], programId: 'old' }, { ...plan.cycles[1], programId: 'next' }] } };
writes.length = 0;
await writeCyclePlan(transaction, 'client', { ...stored.trainingPlan, cycles: stored.trainingPlan.cycles.map((c, i) => i === 0 ? { ...c, closedAt: '2026-09-14' } : c) });
assert.equal(writes[0][1].currentProgramme, 'next', 'transition activates next linked programme');
writes.length = 0;
await writeCyclePlan(transaction, 'client', { ...stored.trainingPlan, cycles: [{ ...stored.trainingPlan.cycles[0], closedAt: '2026-09-14' }, { ...stored.trainingPlan.cycles[1], programId: '' }] });
assert.equal(writes[0][1].currentProgramme, null, 'no linked successor: do not keep completed programme current');
const component = readFileSync(new URL('../src/components/client/TrainingCycles.jsx', import.meta.url), 'utf8');
const sessionComponent = readFileSync(new URL('../src/components/client/CycleSessionList.jsx', import.meta.url), 'utf8');
const keys = [...(component + sessionComponent).matchAll(/tx\('([^']+)'/g)].map(match => match[1]).concat(['hypertrophy','general','strength','recovery','custom','chooseStep','playStep','nextStep']);
for (const language of ['en','es','it','de','ru','ar']) for (const key of keys) assert.ok(cycleTranslations[language][key], `${language}.${key}`);
assert.ok(readFileSync(new URL('../firestore.rules', import.meta.url), 'utf8').includes('"trainingPlan"'));
console.log('Training cycles: 26-week plan, dates, validation, isolated draft copies and six translations plus French fallbacks OK.');
