import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {formatFeetInches,splitInches} from '../src/utils/imperialHeight.js';
import {calculateEntryBmi} from '../src/utils/measurementEntry.js';
assert.equal(formatFeetInches(72),'6′ 0″');
assert.deepEqual(splitInches(71.99),{feet:6,inches:0});
assert.equal(formatFeetInches(''),'—');
assert.equal(calculateEntryBmi(74.8,88,'in','kg'),24.4);
const coach=readFileSync('src/components/ClientView.jsx','utf8');
const panel=readFileSync('src/components/client/ClientMeasurementCharts.jsx','utf8');
const client=readFileSync('src/pages/StatisticsPageClient.jsx','utf8');
assert.ok(coach.includes('bmi:calculateEntryBmi(numeric.taille,numeric.poids)'));
assert.ok(coach.includes('value={entryBmi ?? ""}'));
assert.ok(coach.includes('savingMeasureRef.current'));
assert.ok(coach.includes('latestEntryValue(measures,client,null,read'));
assert.ok(panel.includes('MenuOptionGroup type="checkbox"'));
assert.ok(panel.includes('<MeasurementHelp metric={c.key} profile={profile}'));
assert.ok(!panel.includes('(normal)'));
assert.ok(client.includes('<FeetInchesInput'));
assert.ok(client.includes('<option value="in">ft/in</option>'));
console.log('Coach measurement parity, prefill/BMI, protected save and feet/inches checks passed.');
